{\rtf1\ansi\ansicpg1252\cocoartf2867
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0

\f0\fs24 \cf0 const nodemailer = require('nodemailer');\
\
exports.handler = async function(event, context) \{\
    // Set CORS headers\
    const headers = \{\
        'Access-Control-Allow-Origin': '*',\
        'Access-Control-Allow-Headers': 'Content-Type',\
        'Access-Control-Allow-Methods': 'POST, OPTIONS'\
    \};\
    \
    // Handle preflight request\
    if (event.httpMethod === 'OPTIONS') \{\
        return \{\
            statusCode: 200,\
            headers,\
            body: ''\
        \};\
    \}\
    \
    // Only allow POST requests\
    if (event.httpMethod !== 'POST') \{\
        return \{\
            statusCode: 405,\
            headers,\
            body: JSON.stringify(\{ error: 'Method not allowed' \})\
        \};\
    \}\
    \
    try \{\
        // Parse request body\
        const data = JSON.parse(event.body);\
        \
        // Validate required data\
        if (!data.name || !data.ageRange || !data.gender || !data.group || !data.answers) \{\
            return \{\
                statusCode: 400,\
                headers,\
                body: JSON.stringify(\{ error: 'Missing required fields' \})\
            \};\
        \}\
        \
        // Configure email transporter\
        const transporter = nodemailer.createTransport(\{\
            host: process.env.EMAIL_HOST,\
            port: parseInt(process.env.EMAIL_PORT || '587'),\
            secure: process.env.EMAIL_PORT === '465',\
            auth: \{\
                user: process.env.EMAIL_USER,\
                pass: process.env.EMAIL_PASS\
            \}\
        \});\
        \
        // Format answers for email\
        let answersHtml = '<table border="1" cellpadding="5" cellspacing="0" style="border-collapse: collapse; width: 100%;">';\
        answersHtml += '<tr><th>Q#</th><th>Question</th><th>User Answer</th><th>Correct Answer</th><th>Result</th></tr>';\
        \
        data.answers.forEach((answer, index) => \{\
            const resultColor = answer.isCorrect ? 'green' : 'red';\
            const resultText = answer.isCorrect ? '\uc0\u10003  Correct' : '\u10007  Incorrect';\
            \
            answersHtml += `\
                <tr>\
                    <td>$\{index + 1\}</td>\
                    <td>$\{answer.questionText\}</td>\
                    <td>$\{answer.userAnswer !== null ? answer.userAnswer : 'No answer'\}</td>\
                    <td>$\{answer.correctAnswer\}</td>\
                    <td style="color: $\{resultColor\}; font-weight: bold;">$\{resultText\}</td>\
                </tr>\
            `;\
        \});\
        answersHtml += '</table>';\
        \
        // Create email content\
        const emailHtml = `\
            <h2>Logic & Music Experiment - New Submission</h2>\
            \
            <h3>Participant Information</h3>\
            <p><strong>Name:</strong> $\{data.name\}</p>\
            <p><strong>Age Range:</strong> $\{data.ageRange\}</p>\
            <p><strong>Gender:</strong> $\{data.gender\}</p>\
            <p><strong>Timestamp:</strong> $\{new Date(data.timestamp).toLocaleString()\}</p>\
            \
            <h3>Experiment Details</h3>\
            <p><strong>Assigned Group:</strong> Group $\{data.group\} - $\{data.groupName\}</p>\
            <p><strong>Time Spent:</strong> $\{data.timeSpent\} seconds (out of 120)</p>\
            <p><strong>Auto-submitted:</strong> $\{data.autoSubmitted ? 'Yes (time expired)' : 'No (manual submission)'\}</p>\
            \
            <h3>Results</h3>\
            <p><strong>Score:</strong> $\{data.score\} / $\{data.totalQuestions\}</p>\
            <p><strong>Percentage:</strong> $\{data.percentage\}%</p>\
            \
            <h3>Detailed Answers</h3>\
            $\{answersHtml\}\
            \
            <hr>\
            <p style="color: #666; font-size: 12px;">This email was automatically generated by the Logic & Music Experiment survey system.</p>\
        `;\
        \
        // Send email\
        const info = await transporter.sendMail(\{\
            from: process.env.EMAIL_USER,\
            to: process.env.TARGET_EMAIL,\
            subject: `Logic Experiment \'96 $\{data.name\}`,\
            html: emailHtml\
        \});\
        \
        console.log('Email sent:', info.messageId);\
        \
        return \{\
            statusCode: 200,\
            headers,\
            body: JSON.stringify(\{ \
                success: true, \
                message: 'Survey submitted successfully',\
                messageId: info.messageId\
            \})\
        \};\
        \
    \} catch (error) \{\
        console.error('Error processing submission:', error);\
        \
        return \{\
            statusCode: 500,\
            headers,\
            body: JSON.stringify(\{ \
                error: 'Failed to process submission',\
                details: error.message\
            \})\
        \};\
    \}\
\};}